services:
  app:
    image: ghcr.io/mazapanuwu13/autohost-cloud-lite:latest
    container_name: autohost-cloud-lite
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
