name: CI/CD - Frontend

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write   # ðŸ‘ˆ importante para GHCR

jobs:
  build-and-push:
    name: ðŸ”¨ Build & Push Frontend to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Build & Push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/autohost-cloud-lite:latest
          # o tags: ghcr.io/${{ github.repository_owner }}/autohost-cloud-lite:${{ github.sha }}


  deploy:
    name: ðŸš€ Deploy Frontend (Runner)
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Login a GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull imagen frontend
        run: docker pull ghcr.io/${{ github.repository_owner }}/autohost-cloud-lite:latest

      - name: Reiniciar servicio frontend
        run: docker compose -f ~/projects/autohost-cloud-lite/compose.yml up -d